/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef<any>()
  const { nodes, materials } = useGLTF('models/Lokitable.gltf') as any
  useFrame((state, delta) => (group.current.rotation.y += 0.001));
  return (
    <group ref={group} {...props} dispose={null} scale={[0.1, 0.1, 0.1]} position={[0,-.8,0]} rotation={[Math.PI/8,0,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 13.5]}>
          <group position={[0, 0, -13.5]}>
            <group position={[1.39, 1.07, 18.07]}>
              <mesh geometry={nodes.Wiretype2.geometry} material={materials['Material #26']} position={[13.41, -9.87, -2.04]} />
              <mesh geometry={nodes.Wire1.geometry} material={materials['Material #27']} position={[-4.14, -2.64, -1.09]} />
              <mesh geometry={nodes.Wire2.geometry} material={materials['Material #27']} position={[-9.21, -2.64, -1.09]} />
              <mesh geometry={nodes.Wire3.geometry} material={materials['Material #27']} position={[2.65, -0.1, -1.09]} />
              <mesh geometry={nodes.Wire4.geometry} material={materials['Material #27']} position={[0.32, -2.64, -1.09]} />
              <mesh geometry={nodes.Wire5.geometry} material={materials['Material #27']} position={[0.89, -2.64, -1.09]} />
              <mesh geometry={nodes.Wire006.geometry} material={materials['Material #27']} position={[-8.92, -2.64, -1.09]} />
            </group>
            <group position={[-5.99, -5.93, 16.38]}>
              <group rotation={[Math.PI / 2, Math.PI / 4, 0]}>
                <group scale={[0.53, 0.53, 0.59]}>
                  <group position={[-1.63, 0.06, 0.01]}>
                    <mesh geometry={nodes.Mug.geometry} material={materials['Material #34']} />
                  </group>
                </group>
              </group>
            </group>
            <mesh geometry={nodes.MousePad.geometry} material={materials['Material #25']} position={[11.49, -4.86, 15.51]} rotation={[0, 0, -0.17]} scale={1.47} />
            <mesh geometry={nodes.Monitor2.geometry} material={materials['Material #28']} position={[1.59, 0.22, 16.72]} />
            <mesh geometry={nodes.Monitor3.geometry} material={materials['Material #28']} position={[-8.56, -1.7, 17.44]} />
            <mesh geometry={nodes.Monitor4.geometry} material={materials['Material #28']} position={[12.79, -1.59, 21]} rotation={[0, 0, 0.11]} scale={0.72} />
            <mesh geometry={nodes.Table.geometry} material={materials['Material #29']} position={[0, 0, 14.55]} />
            <mesh geometry={nodes.Monitor1.geometry} material={materials['Material #30']} position={[3.02, 1.66, 22.87]} />
            <mesh geometry={nodes.Keyboard.geometry} material={materials['Material #31']} position={[1.8, -6.49, 15.8]} />
            <mesh geometry={nodes.CPU2.geometry} material={materials['Material #32']} position={[-3.82, -2.45, 22.59]} />
            <mesh geometry={nodes.CPU1.geometry} material={materials['Material #33']} position={[6.16, 3.47, 17.04]} rotation={[0, 0, -0.17]} scale={1.92} />
            <mesh geometry={nodes.Box004.geometry} material={materials['Material #31']} position={[10.96, -5.26, 15.58]} rotation={[0, 0, -2.69]} />
            <mesh geometry={nodes.Monitor1_Glass.geometry} material={materials['Material #35']} position={[3.02, 1.66, 22.87]} />
            <mesh geometry={nodes.Monitor4_Glass.geometry} material={materials['Material #36']} position={[12.79, -1.59, 21]} rotation={[0, 0, 0.11]} scale={0.72} />
            <mesh geometry={nodes.Monitor2_Glass.geometry} material={materials['Material #36']} position={[1.59, 0.22, 16.72]} />
            <mesh geometry={nodes.Monitor3_Glass.geometry} material={materials['Material #36']} position={[-8.56, -1.7, 17.44]} />
            <mesh geometry={nodes.Monitor005.geometry} material={materials['Material #30']} position={[-10.74, -2.52, 22.25]} rotation={[0, 0, 0.78]} scale={0.42} />
            <mesh geometry={nodes.Monitor1_Glass001.geometry} material={materials['Material #35']} position={[-10.76, -2.46, 22.25]} rotation={[0, 0, 0.76]} scale={0.42} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Lokitable.gltf')
